### ISSUE TITLE
Add support for OpenAPI SpecificationExtensions to the SwaggerExample.Create method

### ISSUE THREAD

**Issue by TomBruns** [mattfrear/Swashbuckle.AspNetCore.Filters#223]
I use this package to create multiple examples for request bodies that contain complex POCO objects, ex:

```
        public IEnumerable<SwaggerExample<AuthorizePaymentRequestDTO>> GetExamples()
        {
            yield return SwaggerExample.Create(
                name: "AUTH-SchemeCard-USD",
                summary: "Make a payment (in USD) using a Card",
                description: "This example shows a payment Auth request using a Card (plain text)",
                value: new AuthorizePaymentRequestDTO()
                {
                    MerchantCode = @"test",
                    Amount = new Shared.AmountDTO()
                    {
                        Value = 1000,
                        CurrencyCode = Shared.CurrencyCode.USD
                    }
                } 
         }
```

Would you consider adding support for an **Extensions** property similar to the one here: [OpenApiExample.Extensions Property](https://learn.microsoft.com/en-us/dotnet/api/microsoft.openapi.models.openapiexample.extensions?view=openapi-dotnet)

This is related to OpenAPI [specification extensions](https://spec.openapis.org/oas/v3.0.3#specification-extensions)

This capability could be used by some portal tools to extend example support to include _example specific_ values for:

- Custom HTTP Header Fields   [FromHeader]
- Path parameters [FromRoute]
- Query String parameters [FromQuery]

**Comment by mattfrear** [comment]
Hi Tom

I'm not familiar with OpenApi specification extensions. What do you mean by "example specific values"? What would you like to accomplish?

**Comment by TomBruns** [comment]
Hi Matt

_From the OpenAPI Spec_
**Specification Extensions**
While the OpenAPI Specification tries to accommodate most use cases, additional data can be added to extend the specification at certain points.

The goal would be to emit something like this into to OpenAPI File

```
            examples:
              'AUTH: paymentService_Auth_Request_Credit_Debit_Card':
                summary: ECom (Direct) order (AUTHORIZATION or SALE) w/ Credit or Debit Card
                description: This example shows a complete order for the Direct model
                value:
                  merchantCode: US_MERCHANT_CODE
                  callersReferenceId: Sample 1
                  amount:
                    value: 1000
                    currencyCode: USD
                  paymentMethod:
                    type: card/scheme
                    cardNumber: '4111111111111111'
                    cardVerificationCode: '123'
                    expiryMonth: 1
                    expiryYear: 2025
                    cardHolderName: A Cardholder
                  customerData:
                    billingAddress:
                      postalCode: '12345'
                      country: US
                  customerInteractionType: ECOMMERCE
                x-example-extension: 
                  headers: 
                    - idempotencyKey: 00000000-0000-0000-0000-000000000000
                  parameters:
                    - wpTransactionId:  123456
```

Note the custom extension " x-example-extension: " in the context of this specific example (at the bottom)
